/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contain;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.File;
import java.io.IOException;

/**
 *
 * @author alejandro
 */
public class frmCalculadora extends javax.swing.JFrame {
    
    public float num1;
    public float num2;
    public String operador;

    /**
     * Creates new form frmCalculadora
     */
    public frmCalculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnl_principal = new javax.swing.JPanel();
        lbl_IngresoNumero = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        btn_numSiete = new javax.swing.JButton();
        btn_numCuatro = new javax.swing.JButton();
        btn_numUno = new javax.swing.JButton();
        btn_numCero = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_numOcho = new javax.swing.JButton();
        btn_numNueve = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_numCinco = new javax.swing.JButton();
        btn_numSeis = new javax.swing.JButton();
        btn_numDos = new javax.swing.JButton();
        btn_numTres = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        lbl_opera = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        mn_opciones = new javax.swing.JMenu();
        mit_nuevo = new javax.swing.JMenuItem();
        mit_historial = new javax.swing.JMenuItem();
        mn_ayuda = new javax.swing.JMenu();
        mit_ayuda = new javax.swing.JMenuItem();
        mn_salir = new javax.swing.JMenu();
        mit_salir = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_principal.setBackground(new java.awt.Color(204, 204, 204));

        lbl_IngresoNumero.setBackground(new java.awt.Color(255, 255, 255));
        lbl_IngresoNumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_IngresoNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_IngresoNumero.setOpaque(true);

        btn_borrar.setText("C");
        btn_borrar.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_numSiete.setText("7");
        btn_numSiete.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numSieteActionPerformed(evt);
            }
        });

        btn_numCuatro.setText("4");
        btn_numCuatro.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numCuatroActionPerformed(evt);
            }
        });

        btn_numUno.setText("1");
        btn_numUno.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numUnoActionPerformed(evt);
            }
        });

        btn_numCero.setText("0");
        btn_numCero.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numCeroActionPerformed(evt);
            }
        });

        btn_dividir.setText("/");
        btn_dividir.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });

        btn_multiplicar.setText("*");
        btn_multiplicar.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_resta.setText("-");
        btn_resta.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_numOcho.setText("8");
        btn_numOcho.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numOchoActionPerformed(evt);
            }
        });

        btn_numNueve.setText("9");
        btn_numNueve.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numNueveActionPerformed(evt);
            }
        });

        btn_suma.setText("+");
        btn_suma.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_numCinco.setText("5");
        btn_numCinco.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numCincoActionPerformed(evt);
            }
        });

        btn_numSeis.setText("6");
        btn_numSeis.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numSeisActionPerformed(evt);
            }
        });

        btn_numDos.setText("2");
        btn_numDos.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numDosActionPerformed(evt);
            }
        });

        btn_numTres.setText("3");
        btn_numTres.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_numTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_numTresActionPerformed(evt);
            }
        });

        btn_igual.setText("=");
        btn_igual.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_punto.setText(".");
        btn_punto.setPreferredSize(new java.awt.Dimension(42, 42));
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        lbl_opera.setBackground(new java.awt.Color(204, 204, 204));
        lbl_opera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_opera.setOpaque(true);

        javax.swing.GroupLayout pnl_principalLayout = new javax.swing.GroupLayout(pnl_principal);
        pnl_principal.setLayout(pnl_principalLayout);
        pnl_principalLayout.setHorizontalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addComponent(lbl_opera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_IngresoNumero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnl_principalLayout.createSequentialGroup()
                                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_principalLayout.createSequentialGroup()
                                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btn_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(btn_numSiete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_numCuatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_numUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_numDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_numOcho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_numCinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btn_numCero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_numSeis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(btn_numNueve, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_numTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_multiplicar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_punto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28))))
        );
        pnl_principalLayout.setVerticalGroup(
            pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_opera, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_IngresoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_numSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_numCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_numUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_numDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_numCero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_principalLayout.createSequentialGroup()
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_numOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_numNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mn_opciones.setText("Opciones");

        mit_nuevo.setText("Nuevo");
        mit_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_nuevoActionPerformed(evt);
            }
        });
        mn_opciones.add(mit_nuevo);

        mit_historial.setText("Historial");
        mit_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_historialActionPerformed(evt);
            }
        });
        mn_opciones.add(mit_historial);

        jMenuBar.add(mn_opciones);

        mn_ayuda.setText("Ayuda");

        mit_ayuda.setText("Ayuda");
        mit_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_ayudaActionPerformed(evt);
            }
        });
        mn_ayuda.add(mit_ayuda);

        jMenuBar.add(mn_ayuda);

        mn_salir.setText("Salir");

        mit_salir.setText("Salir");
        mit_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mit_salirMouseClicked(evt);
            }
        });
        mit_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_salirActionPerformed(evt);
            }
        });
        mn_salir.add(mit_salir);

        jMenuBar.add(mn_salir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_principal, javax.swing.GroupLayout.PREFERRED_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mit_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_nuevoActionPerformed
        // TODO add your handling code here:
        agregarNuevoAlHistorial();
        lbl_IngresoNumero.setText("");
    }//GEN-LAST:event_mit_nuevoActionPerformed
    
    private void agregarNuevoAlHistorial() {
        try {
            File archivo = new File("historial.txt");
            FileWriter escritor = new FileWriter(archivo, true);
            
            escritor.write("Nuevo\n");
            
            escritor.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void mit_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_historialActionPerformed
        // TODO add your handling code here:
        frmHistorial frm = new frmHistorial();
        frm.setVisible(true);
    }//GEN-LAST:event_mit_historialActionPerformed
    
    public String noCero(float resultado) {
        String retorno = "";
        retorno = Float.toString(resultado);
        
        if (resultado % 1 == 0) {
            retorno = retorno.substring(0, retorno.length() - 2);
        }
        return retorno;
    }
    
    private void historial(String operacion) {
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("mostrarHistorial.txt", true));
            writer.append(operacion);
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void mit_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_ayudaActionPerformed
        // TODO add your handling code here:
        frmAyuda frm = new frmAyuda();
        frm.setVisible(true);
    }//GEN-LAST:event_mit_ayudaActionPerformed

    private void mit_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mit_salirMouseClicked
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_mit_salirMouseClicked

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
        if (!this.lbl_IngresoNumero.getText().contains(".")) {
            this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + ".");
        }
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
        this.num2 = Float.parseFloat(this.lbl_IngresoNumero.getText());
        this.lbl_opera.setText("");

        switch (this.operador) {
            case "+":
            this.lbl_IngresoNumero.setText(noCero(this.num1 + this.num2));
            break;
            case "-":
            this.lbl_IngresoNumero.setText(noCero(this.num1 - this.num2));
            break;
            case "*":
            this.lbl_IngresoNumero.setText(noCero(this.num1 * this.num2));
            break;
            case "/":
            if (this.num2 == 0) {
                this.lbl_IngresoNumero.setText("ImposibleDividirEntreCero");
            } else {
                this.lbl_IngresoNumero.setText(noCero(this.num1 / this.num2));
            }
            break;
        }
        String resultado = this.lbl_IngresoNumero.getText();
        this.lbl_opera.setText(this.lbl_opera.getText() + "=");
        historial(this.num1 + " " + this.operador + " " + this.num2 + " = " + resultado);
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_numTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numTresActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "3");
    }//GEN-LAST:event_btn_numTresActionPerformed

    private void btn_numDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numDosActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "2");
    }//GEN-LAST:event_btn_numDosActionPerformed

    private void btn_numSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numSeisActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "6");
    }//GEN-LAST:event_btn_numSeisActionPerformed

    private void btn_numCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numCincoActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "5");
    }//GEN-LAST:event_btn_numCincoActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // TODO add your handling code here:
        this.num1 = Float.parseFloat(this.lbl_IngresoNumero.getText());
        this.operador = "+";
        this.lbl_opera.setText("+");
        this.lbl_IngresoNumero.setText("");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_numNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numNueveActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "9");
    }//GEN-LAST:event_btn_numNueveActionPerformed

    private void btn_numOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numOchoActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "8");
    }//GEN-LAST:event_btn_numOchoActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // TODO add your handling code here:
        this.num1 = Float.parseFloat(this.lbl_IngresoNumero.getText());
        this.operador = "-";
        this.lbl_opera.setText("-");
        this.lbl_IngresoNumero.setText("");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        // TODO add your handling code here:
        this.num1 = Float.parseFloat(this.lbl_IngresoNumero.getText());
        this.operador = "*";
        this.lbl_opera.setText("*");
        this.lbl_IngresoNumero.setText("");
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        // TODO add your handling code here:
        this.num1 = Float.parseFloat(this.lbl_IngresoNumero.getText());
        this.operador = "/";
        this.lbl_opera.setText("/");
        this.lbl_IngresoNumero.setText("");
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_numCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numCeroActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "0");
    }//GEN-LAST:event_btn_numCeroActionPerformed

    private void btn_numUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numUnoActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "1");
    }//GEN-LAST:event_btn_numUnoActionPerformed

    private void btn_numCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numCuatroActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "4");
    }//GEN-LAST:event_btn_numCuatroActionPerformed

    private void btn_numSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_numSieteActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText(this.lbl_IngresoNumero.getText() + "7");
    }//GEN-LAST:event_btn_numSieteActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
        this.lbl_IngresoNumero.setText("");
        this.lbl_opera.setText("");
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void mit_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_salirActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_mit_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_numCero;
    private javax.swing.JButton btn_numCinco;
    private javax.swing.JButton btn_numCuatro;
    private javax.swing.JButton btn_numDos;
    private javax.swing.JButton btn_numNueve;
    private javax.swing.JButton btn_numOcho;
    private javax.swing.JButton btn_numSeis;
    private javax.swing.JButton btn_numSiete;
    private javax.swing.JButton btn_numTres;
    private javax.swing.JButton btn_numUno;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel lbl_IngresoNumero;
    private javax.swing.JLabel lbl_opera;
    private javax.swing.JMenuItem mit_ayuda;
    private javax.swing.JMenuItem mit_historial;
    private javax.swing.JMenuItem mit_nuevo;
    private javax.swing.JMenuItem mit_salir;
    private javax.swing.JMenu mn_ayuda;
    private javax.swing.JMenu mn_opciones;
    private javax.swing.JMenu mn_salir;
    private javax.swing.JPanel pnl_principal;
    // End of variables declaration//GEN-END:variables

}
